# Dev env compose file

version: '2'

volumes:
    pgdata:
    pglogs:

services:

    django:
        build:
            context: ./../../
            dockerfile: ./docker/stage/Dockerfile-stage
        volumes:
            - ./../../:/urbana
        working_dir: /urbana/urbana
        command: bash -c ". ../docker/stage/run_django.sh"
        ports:
            - 80:80
            - 35729:35729
        depends_on:
            - pg_database
        env_file: stage.env

    pg_database:
        image: postgres:9.5.3
        # secret strings are in the file
        env_file: stage.env
        volumes:
            # override postgres image Dockerfile data volume
            - pgdata:/var/lib/postgresql/data
            - pglogs:/var/log/postgresql
            - ./dumps:/dumps  # volume mounted to get dump files out of container
        ports:
            # expose ports to the docker host for debug purposes
            - 5432:5432